// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantPalace.DataAccess.Data;

#nullable disable

namespace PlantPalace.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231018084734_AddPoductandseeds")]
    partial class AddPoductandseeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlantPalace.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categorries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Indoor"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            Name = "Outdoor"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 1,
                            Name = "Tree"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 1,
                            Name = "Hanging"
                        });
                });

            modelBuilder.Entity("PlantPalace.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ListPrice = 100.0,
                            Name = "Product 1",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75
                        },
                        new
                        {
                            Id = 2,
                            ListPrice = 100.0,
                            Name = "Product 2",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75
                        },
                        new
                        {
                            Id = 3,
                            ListPrice = 100.0,
                            Name = "Product 3",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75
                        },
                        new
                        {
                            Id = 4,
                            ListPrice = 100.0,
                            Name = "Product 4",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75
                        },
                        new
                        {
                            Id = 5,
                            ListPrice = 100.0,
                            Name = "Product 5",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75
                        },
                        new
                        {
                            Id = 6,
                            ListPrice = 100.0,
                            Name = "Product 6",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75
                        },
                        new
                        {
                            Id = 7,
                            ListPrice = 100.0,
                            Name = "Product 7",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75
                        },
                        new
                        {
                            Id = 8,
                            ListPrice = 100.0,
                            Name = "Product 8",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75
                        },
                        new
                        {
                            Id = 9,
                            ListPrice = 100.0,
                            Name = "Product 9",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75
                        },
                        new
                        {
                            Id = 10,
                            ListPrice = 100.0,
                            Name = "Product 10",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
