// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantPalace.DataAccess.Data;

#nullable disable

namespace PlantPalace.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231018123002_addImageUrltoProductwithEmty")]
    partial class addImageUrltoProductwithEmty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlantPalace.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categorries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Indoor"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            Name = "Outdoor"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 1,
                            Name = "Tree"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 1,
                            Name = "Hanging"
                        });
                });

            modelBuilder.Entity("PlantPalace.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("categoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "",
                            ListPrice = 100.0,
                            Name = "Product 1",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75,
                            categoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "",
                            ListPrice = 100.0,
                            Name = "Product 2",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75,
                            categoryId = 4
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "",
                            ListPrice = 100.0,
                            Name = "Product 3",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75,
                            categoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "",
                            ListPrice = 100.0,
                            Name = "Product 4",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75,
                            categoryId = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "",
                            ListPrice = 100.0,
                            Name = "Product 5",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75,
                            categoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "",
                            ListPrice = 100.0,
                            Name = "Product 6",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75,
                            categoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "",
                            ListPrice = 100.0,
                            Name = "Product 7",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75,
                            categoryId = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "",
                            ListPrice = 100.0,
                            Name = "Product 8",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75,
                            categoryId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "",
                            ListPrice = 100.0,
                            Name = "Product 9",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75,
                            categoryId = 4
                        },
                        new
                        {
                            Id = 10,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ImageUrl = "",
                            ListPrice = 100.0,
                            Name = "Product 10",
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.75,
                            categoryId = 3
                        });
                });

            modelBuilder.Entity("PlantPalace.Models.Product", b =>
                {
                    b.HasOne("PlantPalace.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
